pipeline {
    agent any

    environment {
        // Tomcat installation path
        TOMCAT_HOME = "C:\\apache-tomcat-9.0.117-windows-x64"

        // Correct WAR file name (as generated by Maven)
        WAR_FILE = "${WORKSPACE}\\target\\myapp.war"
    }

    stages {

        stage('Code Checkout') {
            steps {
                echo "Checking out code from Git"
                git branch: 'master', url: 'https://github.com/Vishal201927/my-project.git'
            }
        }

        stage('Build') {
            steps {
                echo "Building the project"
                bat 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                echo "Running tests"
                bat 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying WAR to Tomcat"
                bat "copy /Y \"${WAR_FILE}\" \"${TOMCAT_HOME}\\webapps\\myapp.war\""
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}
